services:
  postgres:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    env_file: .env
    restart: always

  web:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'
    env_file: .env
    depends_on:
      - postgres

  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    restart: always
